# Generated by Django 4.0.5 on 2023-03-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_user_ids',
        ),
    ]
